In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.


In [2]:
e = np.identity(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
e5 = e * 5
e5

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [4]:
p = np.linalg.inv(e5)
p

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

Вычислите определитель



In [7]:
matrix = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [9]:
round(np.linalg.det(matrix))

60.0

Вычислите матрицу, обратную данной:


In [11]:
np.linalg.inv(matrix)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

Приведите пример матрицы 4х4, ранг которой равен 1.


In [14]:
rank_1 = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [3, 6, 9, 12], [4, 8, 12, 16]])
print(rank_1)
print(f'ранг данной матрицы равен = {np.linalg.matrix_rank(rank_1, 0.00001):.0f}')

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
ранг данной матрицы равен = 1


Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)


In [15]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)
np.dot(a, b)

42.0

In [16]:
1 * 2 + 5 * 8

42

Вычислите смешанное произведение трех векторов:


In [17]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3], float)

In [18]:
v = np.cross(a, b)
np.inner(v, c)

228.5